In [ ]:
# Data Pre-Processing

In [33]:
# importing required libraries
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [5]:
train = pd.read_csv('titanic-train.csv')
train.shape

(891, 11)

In [7]:
train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [8]:
test = pd.read_csv('titanic-test.csv')
test.shape

(418, 11)

In [9]:
test

PassengerId Survived  Pclass     Sex   Age  SibSp  Parch  \
0            892        ?       3    male  34.5      0      0   
1            893        ?       3  female  47.0      1      0   
2            894        ?       2    male  62.0      0      0   
3            895        ?       3    male  27.0      0      0   
4            896        ?       3  female  22.0      1      1   
..           ...      ...     ...     ...   ...    ...    ...   
413         1305        ?       3    male   NaN      0      0   
414         1306        ?       1  female  39.0      0      0   
415         1307        ?       3    male  38.5      0      0   
416         1308        ?       3    male   NaN      0      0   
417         1309        ?       3    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [14]:
# converting cabin to binary attribute using dummy variable
train['Cabin'] = train["Cabin"].apply(lambda x: 0 if type(x) == float else 1)
test['Cabin'] = test["Cabin"].apply(lambda x: 0 if type(x) == float else 1)

# converting sex cateogorical variable to dummy variable
train['Sex'] = train["Sex"].replace({'male':0,'female':1})
test['Sex'] = test["Sex"].replace({'male':0,'female':1})

In [16]:
full_data = [train,test]
full_data

[     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch            Ticket  \
 0              1         0       3    0  22.0      1      0         A/5 21171   
 1              2         1       1    1  38.0      1      0          PC 17599   
 2              3         1       3    1  26.0      0      0  STON/O2. 3101282   
 3              4         1       1    1  35.0      1      0            113803   
 4              5         0       3    0  35.0      0      0            373450   
 ..           ...       ...     ...  ...   ...    ...    ...               ...   
 886          887         0       2    0  27.0      0      0            211536   
 887          888         1       1    1  19.0      0      0            112053   
 888          889         0       3    1   NaN      1      2        W./C. 6607   
 889          890         1       1    0  26.0      0      0            111369   
 890          891         0       3    0  32.0      0      0            370376   
 
         Fare 

In [19]:
# Remove all NULLS in the Age column
for dataset in full_data:
    age_avg = dataset['Age'].mean()
    age_std = dataset['Age'].std()
    age_null_count = dataset['Age'].isnull().sum()
    age_null_random_list = np.random.randint(age_avg - age_std, age_avg + age_std, size=age_null_count)
    # Next line has been improved to avoid warning
    dataset.loc[np.isnan(dataset['Age']), 'Age'] = age_null_random_list
    dataset['Age'] = dataset['Age'].astype(int)

In [26]:
X_train = train[['Sex','Pclass','Age','SibSp','Parch','Cabin']]
Y_train = train['Survived']
X_test = test[['Sex','Pclass','Age','SibSp','Parch','Cabin']]

#### Exercise:kNN

#### Using the Titanic data: Create a kNN model Report accuracy when number of neighbors = {1, 3, 5, 7}. Pick the best k value and then change the weighted distance metric. Report if distance weighting helps or not.

In [40]:
def knn_model(n_neighbors, X_train, Y_train):
    neigh = KNeighborsClassifier(n_neighbors=n_neighbors)
    neigh.fit(X_train, Y_train)
    neigh_pred = neigh.predict(X_train)
    return neigh_pred

In [35]:
def performace(test_results, gold_results):
    tab = pd.crosstab(test_results,gold_results,rownames=['Actual'],colnames=['Predicted'])
    print(tab)

    matrix = confusion_matrix(test_results,gold_results)
    print('Confusion matrix : \n',matrix)

    # classification report for precision, recall f1-score and accuracy
    matrix = classification_report(test_results,gold_results)
    print('Classification report : \n',matrix)

In [41]:
neigh_pred = knn_model(1,X_train,Y_train)
neigh_pred

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [42]:
performace(Y_train,neigh_pred)

Predicted    0    1
Actual             
0          478   71
1           35  307
Confusion matrix : 
 [[478  71]
 [ 35 307]]
Classification report : 
               precision    recall  f1-score   support

           0       0.93      0.87      0.90       549
           1       0.81      0.90      0.85       342

    accuracy                           0.88       891
   macro avg       0.87      0.88      0.88       891
weighted avg       0.89      0.88      0.88       891



###### ACCURACY OF KNN (K=1) 0.88

In [44]:
neigh_pred = knn_model(3,X_train,Y_train)
performace(Y_train,neigh_pred)

Predicted    0    1
Actual             
0          500   49
1           70  272
Confusion matrix : 
 [[500  49]
 [ 70 272]]
Classification report : 
               precision    recall  f1-score   support

           0       0.88      0.91      0.89       549
           1       0.85      0.80      0.82       342

    accuracy                           0.87       891
   macro avg       0.86      0.85      0.86       891
weighted avg       0.87      0.87      0.87       891



###### ACCURACY OF KNN (K=3) 0.87

In [45]:
neigh_pred = knn_model(5,X_train,Y_train)
performace(Y_train,neigh_pred)

Predicted    0    1
Actual             
0          500   49
1           86  256
Confusion matrix : 
 [[500  49]
 [ 86 256]]
Classification report : 
               precision    recall  f1-score   support

           0       0.85      0.91      0.88       549
           1       0.84      0.75      0.79       342

    accuracy                           0.85       891
   macro avg       0.85      0.83      0.84       891
weighted avg       0.85      0.85      0.85       891



##### ACCURACY OF KNN (K=5) 0.87

In [47]:
neigh_pred = knn_model(7,X_train,Y_train)
performace(Y_train,neigh_pred)

Predicted    0    1
Actual             
0          496   53
1           98  244
Confusion matrix : 
 [[496  53]
 [ 98 244]]
Classification report : 
               precision    recall  f1-score   support

           0       0.84      0.90      0.87       549
           1       0.82      0.71      0.76       342

    accuracy                           0.83       891
   macro avg       0.83      0.81      0.82       891
weighted avg       0.83      0.83      0.83       891



##### ACCURACY OF KNN (K=7) 0.83

In [53]:
## choosing the model with one nearest neighbour. It has the highest accuracy of 0.88

# change the weighted distance metric
knn_clf = KNeighborsClassifier(n_neighbors=3, weights='distance')
knn_clf.fit(X_train, Y_train)
knn_pred = knn_clf.predict(X_train)

In [54]:
performace(Y_train, knn_pred)

# performance improved the accuacy of k=3

Predicted    0    1
Actual             
0          531   18
1           54  288
Confusion matrix : 
 [[531  18]
 [ 54 288]]
Classification report : 
               precision    recall  f1-score   support

           0       0.91      0.97      0.94       549
           1       0.94      0.84      0.89       342

    accuracy                           0.92       891
   macro avg       0.92      0.90      0.91       891
weighted avg       0.92      0.92      0.92       891

